/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JLabel;

/**
 *
 * @author arief budiman
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    FlowLayout layout =  new FlowLayout();
    menuHome pl1;
    menuAtas pl2;
   // panel3 pl3;
    MenuBantuan menuBantuan;
    menuTentang menuTentang;
    
    public MenuUtama() {
        initComponents();
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
       
        pl1 = new menuHome();
        pl2 = new menuAtas();
       // pl3 = new panel3();
        menuBantuan = new MenuBantuan();
        menuTentang = new menuTentang();
        DynamicPanel.setLayout(layout);
        //GridBagConstraints c = new GridBagConstraints();
        //c.gridx = 0;
        //c.gridy = 0;
        DynamicPanel.add(pl1);
       // c.gridx = 0;
        //c.gridy = 0;
        DynamicPanel.add(pl2);
        //DynamicPanel.add(pl3);
        //c.gridx = 0;
        //c.gridy = 0;
        DynamicPanel.add(menuBantuan);
        DynamicPanel.add(menuTentang);
        setColor(btnHome);
        resetColor(btnMenuIPA);
        setColorMenu(lblBeranda);
        resetColorMenu(lblBantuan);
        resetColorMenu(lblPrediksi);
        resetColorMenu(lblKeluar);
        ind_menu1.setOpaque(true);
        ind_menu2.setOpaque(false);
        ind_menu6.setOpaque(false);
        ind_menu4.setOpaque(false);
        ind_menu5.setOpaque(false);
        pl1.setVisible(true);
        pl2.setVisible(false);
       // pl3.setVisible(false);
        menuBantuan.setVisible(false);
        menuTentang.setVisible(false);
    }
    
     void setColor(JPanel panel){
        panel.setBackground(new Color(47,79,106));
    }
     
     void resetColor(JPanel panel){
         panel.setBackground(new Color(59,102,145));
     }
     
      void setColorMenu(JLabel label){
        label.setForeground(new Color(90,204,245));
    }
     
     void resetColorMenu(JLabel label){
         label.setForeground(new Color(240,240,240));
     }
     
     void doExit() {
      int confirm = JOptionPane.showConfirmDialog(this,
      "Anda yakin untuk keluar?",
      "Konfirmasi",
      JOptionPane.YES_NO_OPTION,
      JOptionPane.QUESTION_MESSAGE);

      if (confirm == JOptionPane.YES_OPTION) {
          System.exit(0);
      }
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        parent = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        ind_menu1 = new javax.swing.JPanel();
        icon2 = new javax.swing.JLabel();
        lblBeranda = new javax.swing.JLabel();
        btnMenuIPA = new javax.swing.JPanel();
        ind_menu2 = new javax.swing.JPanel();
        icon3 = new javax.swing.JLabel();
        lblPrediksi = new javax.swing.JLabel();
        btnMenuBantuan = new javax.swing.JPanel();
        ind_menu4 = new javax.swing.JPanel();
        icon5 = new javax.swing.JLabel();
        lblBantuan = new javax.swing.JLabel();
        btnMenuKeluar = new javax.swing.JPanel();
        ind_menu5 = new javax.swing.JPanel();
        icon6 = new javax.swing.JLabel();
        lblKeluar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnMenuTentang = new javax.swing.JPanel();
        ind_menu6 = new javax.swing.JPanel();
        icon7 = new javax.swing.JLabel();
        lblTentang = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        DynamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        parent.setBackground(new java.awt.Color(104, 141, 171));

        sidepane.setBackground(new java.awt.Color(59, 102, 145));

        btnHome.setBackground(new java.awt.Color(59, 102, 145));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
        });
        btnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_menu1.setBackground(new java.awt.Color(90, 204, 245));
        ind_menu1.setOpaque(false);

        javax.swing.GroupLayout ind_menu1Layout = new javax.swing.GroupLayout(ind_menu1);
        ind_menu1.setLayout(ind_menu1Layout);
        ind_menu1Layout.setHorizontalGroup(
            ind_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ind_menu1Layout.setVerticalGroup(
            ind_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btnHome.add(ind_menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3, 50));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home3.png"))); // NOI18N
        btnHome.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 37, 40));

        lblBeranda.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblBeranda.setForeground(new java.awt.Color(255, 255, 255));
        lblBeranda.setText("Home");
        btnHome.add(lblBeranda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        btnMenuIPA.setBackground(new java.awt.Color(59, 102, 145));
        btnMenuIPA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuIPAMousePressed(evt);
            }
        });
        btnMenuIPA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_menu2.setBackground(new java.awt.Color(90, 204, 245));
        ind_menu2.setOpaque(false);

        javax.swing.GroupLayout ind_menu2Layout = new javax.swing.GroupLayout(ind_menu2);
        ind_menu2.setLayout(ind_menu2Layout);
        ind_menu2Layout.setHorizontalGroup(
            ind_menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ind_menu2Layout.setVerticalGroup(
            ind_menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btnMenuIPA.add(ind_menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3, 50));

        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/jurusan.png"))); // NOI18N
        btnMenuIPA.add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 37, 40));

        lblPrediksi.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblPrediksi.setForeground(new java.awt.Color(255, 255, 255));
        lblPrediksi.setText("Prediksi");
        btnMenuIPA.add(lblPrediksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        btnMenuBantuan.setBackground(new java.awt.Color(59, 102, 145));
        btnMenuBantuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuBantuanMousePressed(evt);
            }
        });
        btnMenuBantuan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_menu4.setBackground(new java.awt.Color(90, 204, 245));
        ind_menu4.setOpaque(false);

        javax.swing.GroupLayout ind_menu4Layout = new javax.swing.GroupLayout(ind_menu4);
        ind_menu4.setLayout(ind_menu4Layout);
        ind_menu4Layout.setHorizontalGroup(
            ind_menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ind_menu4Layout.setVerticalGroup(
            ind_menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btnMenuBantuan.add(ind_menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3, 50));

        icon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bantuan.png"))); // NOI18N
        btnMenuBantuan.add(icon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 37, 40));

        lblBantuan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblBantuan.setForeground(new java.awt.Color(255, 255, 255));
        lblBantuan.setText("Bantuan");
        btnMenuBantuan.add(lblBantuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        btnMenuKeluar.setBackground(new java.awt.Color(59, 102, 145));
        btnMenuKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuKeluarMousePressed(evt);
            }
        });
        btnMenuKeluar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_menu5.setBackground(new java.awt.Color(255, 153, 51));
        ind_menu5.setOpaque(false);

        javax.swing.GroupLayout ind_menu5Layout = new javax.swing.GroupLayout(ind_menu5);
        ind_menu5.setLayout(ind_menu5Layout);
        ind_menu5Layout.setHorizontalGroup(
            ind_menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ind_menu5Layout.setVerticalGroup(
            ind_menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btnMenuKeluar.add(ind_menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3, 50));

        icon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/keluar.png"))); // NOI18N
        btnMenuKeluar.add(icon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 37, 40));

        lblKeluar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblKeluar.setForeground(new java.awt.Color(255, 255, 255));
        lblKeluar.setText("Keluar");
        btnMenuKeluar.add(lblKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(104, 141, 171));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(104, 141, 171));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(104, 141, 171));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(104, 141, 171));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(104, 141, 171));
        jPanel5.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(104, 141, 171));
        jPanel6.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        btnMenuTentang.setBackground(new java.awt.Color(59, 102, 145));
        btnMenuTentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuTentangMousePressed(evt);
            }
        });
        btnMenuTentang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_menu6.setBackground(new java.awt.Color(90, 204, 245));
        ind_menu6.setOpaque(false);

        javax.swing.GroupLayout ind_menu6Layout = new javax.swing.GroupLayout(ind_menu6);
        ind_menu6.setLayout(ind_menu6Layout);
        ind_menu6Layout.setHorizontalGroup(
            ind_menu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ind_menu6Layout.setVerticalGroup(
            ind_menu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btnMenuTentang.add(ind_menu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 3, 50));

        icon7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tentang.png"))); // NOI18N
        btnMenuTentang.add(icon7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 37, 40));

        lblTentang.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblTentang.setForeground(new java.awt.Color(255, 255, 255));
        lblTentang.setText("Tentang");
        btnMenuTentang.add(lblTentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel7.setBackground(new java.awt.Color(104, 141, 171));
        jPanel7.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidepaneLayout = new javax.swing.GroupLayout(sidepane);
        sidepane.setLayout(sidepaneLayout);
        sidepaneLayout.setHorizontalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMenuIPA, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
            .addComponent(btnMenuBantuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMenuKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
            .addComponent(btnMenuTentang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
        );
        sidepaneLayout.setVerticalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMenuIPA, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMenuBantuan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMenuTentang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DynamicPanel.setBackground(new java.awt.Color(104, 141, 171));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout parentLayout = new javax.swing.GroupLayout(parent);
        parent.setLayout(parentLayout);
        parentLayout.setHorizontalGroup(
            parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentLayout.createSequentialGroup()
                .addComponent(sidepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        parentLayout.setVerticalGroup(
            parentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DynamicPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        // TODO add your handling code here:
        
        setColor(btnHome);
        resetColor(btnMenuIPA);
        resetColor(btnMenuTentang);
        resetColor(btnMenuBantuan);
        resetColor(btnMenuKeluar);
        ind_menu1.setOpaque(true);
        ind_menu2.setOpaque(false);
        ind_menu6.setOpaque(false);
        ind_menu4.setOpaque(false);
        ind_menu5.setOpaque(false);
        
        pl1.setVisible(true);
        pl2.setVisible(false);
        menuBantuan.setVisible(false);
        menuTentang.setVisible(false);
        setColorMenu(lblBeranda);
        resetColorMenu(lblBantuan);
        resetColorMenu(lblPrediksi);
        resetColorMenu(lblKeluar);
        resetColorMenu(lblTentang);
    
       
        
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnMenuIPAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuIPAMousePressed
        // TODO add your handling code here:
               
        setColor(btnMenuIPA);
        resetColor(btnHome);
        resetColor(btnMenuTentang);
        resetColor(btnMenuBantuan);
        resetColor(btnMenuKeluar);
        ind_menu2.setOpaque(true);
        ind_menu1.setOpaque(false);
        ind_menu6.setOpaque(false);
        ind_menu4.setOpaque(false);
        ind_menu5.setOpaque(false);
        setColorMenu(lblPrediksi);
        resetColorMenu(lblBantuan);
        resetColorMenu(lblBeranda);
        resetColorMenu(lblKeluar);
        resetColorMenu(lblTentang); 
       
        pl2.setVisible(true);
        pl1.setVisible(false);
       // pl3.setVisible(false);
        menuBantuan.setVisible(false);
        menuTentang.setVisible(false);
    }//GEN-LAST:event_btnMenuIPAMousePressed

    private void btnMenuBantuanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuBantuanMousePressed
        // TODO add your handling code here:
        setColor(btnMenuBantuan);
        resetColor(btnMenuIPA);
        //resetColor(btnMenuIPS);
        resetColor(btnHome);
        resetColor(btnMenuKeluar);
        resetColor(btnMenuTentang);
        ind_menu4.setOpaque(true);
        ind_menu2.setOpaque(false);
        ind_menu6.setOpaque(false);
        ind_menu1.setOpaque(false);
        ind_menu5.setOpaque(false);
        
        setColorMenu(lblBantuan);
        resetColorMenu(lblBeranda);
        resetColorMenu(lblPrediksi);
        resetColorMenu(lblKeluar);
        resetColorMenu(lblTentang); 
        pl2.setVisible(false);
        pl1.setVisible(false);
        menuBantuan.setVisible(true);
        menuTentang.setVisible(false);
    }//GEN-LAST:event_btnMenuBantuanMousePressed

    private void btnMenuKeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuKeluarMousePressed
        // TODO add your handling code here:
        setColor(btnMenuKeluar);
        resetColor(btnMenuIPA);
       // resetColor(btnMenuIPS);
        resetColor(btnHome);
        resetColor(btnMenuBantuan);
        resetColor(btnMenuTentang);
        ind_menu5.setOpaque(true);
        ind_menu2.setOpaque(false);
        ind_menu6.setOpaque(false);
        ind_menu1.setOpaque(false);
        ind_menu4.setOpaque(false);
        
        setColorMenu(lblKeluar);
        resetColorMenu(lblBantuan);
        resetColorMenu(lblPrediksi);
        resetColorMenu(lblBeranda);
        resetColorMenu(lblTentang);                                                 
        doExit();
    }//GEN-LAST:event_btnMenuKeluarMousePressed

    private void btnMenuTentangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuTentangMousePressed
        // TODO add your handling code here:
        setColor(btnMenuTentang);
        resetColor(btnMenuIPA);
        //resetColor(btnMenuIPS);
        resetColor(btnHome);
        resetColor(btnMenuKeluar);
        resetColor(btnMenuBantuan);
        ind_menu4.setOpaque(false);
        ind_menu2.setOpaque(false);
        ind_menu6.setOpaque(true);
        ind_menu1.setOpaque(false);
        ind_menu5.setOpaque(false);
        
        setColorMenu(lblTentang);
        resetColorMenu(lblBeranda);
        resetColorMenu(lblPrediksi);
        resetColorMenu(lblKeluar);
        resetColorMenu(lblBantuan); 
        pl2.setVisible(false);
        pl1.setVisible(false);
        menuBantuan.setVisible(false);
        menuTentang.setVisible(true);
    }//GEN-LAST:event_btnMenuTentangMousePressed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
        
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnMenuBantuan;
    private javax.swing.JPanel btnMenuIPA;
    private javax.swing.JPanel btnMenuKeluar;
    private javax.swing.JPanel btnMenuTentang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon5;
    private javax.swing.JLabel icon6;
    private javax.swing.JLabel icon7;
    private javax.swing.JPanel ind_menu1;
    private javax.swing.JPanel ind_menu2;
    private javax.swing.JPanel ind_menu4;
    private javax.swing.JPanel ind_menu5;
    private javax.swing.JPanel ind_menu6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblBantuan;
    private javax.swing.JLabel lblBeranda;
    private javax.swing.JLabel lblKeluar;
    private javax.swing.JLabel lblPrediksi;
    private javax.swing.JLabel lblTentang;
    private javax.swing.JPanel parent;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
