/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Controller.controlEvaluasi;
import java.awt.Cursor;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author arief budiman
 */
public class menuEvaluasi extends javax.swing.JPanel {
        controlEvaluasi ce;
    /**
     * Creates new form test2
     */
    public menuEvaluasi() {
        initComponents();
        initialization();
    }
    
    private void initialization() {
        ce = new controlEvaluasi();
        lblerror.setText("");
        ce.showTahunAjaranModel(tblTahunModel);
        ce.showTahunAjaranUji(tblTahunUji);
        tblCM.setRowHeight(0, 25);
        tblCM.setRowHeight(1, 25);
        tblCM.setRowHeight(2, 25);
        txtKNN.setEnabled(false);
        btnProses.setEnabled(false);
        jPanel21.setVisible(false);
        jPanel22.setVisible(false);
        txtArea.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbltotaldataModel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblTahunModel = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblDatasetModel = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbltotaldatauji = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTahunUji = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDatasetUji = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        multiTesting = new javax.swing.JRadioButton();
        singleTesting = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtKNN = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        lblerror = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblCM = new javax.swing.JTable();
        lblAkurasi = new javax.swing.JLabel();
        lblRecall = new javax.swing.JLabel();
        lblPrecision = new javax.swing.JLabel();
        lblNilaiK = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jPanel21 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        panelChart = new javax.swing.JPanel();
        panelChart2 = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(59, 102, 145));

        jTabbedPane1.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dataset Model", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Cn", 0, 14))); // NOI18N
        jPanel10.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        jLabel6.setText("Jumlah Data :");

        lbltotaldataModel.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        lbltotaldataModel.setText("0 Data");

        tblTahunModel.setBackground(new java.awt.Color(90, 204, 245));
        tblTahunModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dataset", "Pilih"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTahunModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTahunModelMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblTahunModel);

        tblDatasetModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "NAMA", "Mean_SMS1", "Mean_SMS2", "Mean_SMS3", "Mean_SMS4", "Mean_SMS5", "Mean_SMS6", "MTK1", "BINDO1", "BING1", "Peminatan1", "Mean1", "MTK2", "BINDO2", "BING2", "Peminatan2", "Mean2", "Keterangan", "TransKeterangan", "Hasil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tblDatasetModel);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbltotaldataModel))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbltotaldataModel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dataset Uji", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Cn", 0, 14))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        jLabel5.setText("Jumlah Data :");

        lbltotaldatauji.setFont(new java.awt.Font("Roboto Lt", 1, 12)); // NOI18N
        lbltotaldatauji.setText("0 Data");

        tblTahunUji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dataset", "Pilih"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblTahunUji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTahunUjiMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblTahunUji);

        tblDatasetUji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "NAMA", "Mean_SMS1", "Mean_SMS2", "Mean_SMS3", "Mean_SMS4", "Mean_SMS5", "Mean_SMS6", "MTK1", "BINDO1", "BING1", "Peminatan1", "Mean1", "MTK2", "BINDO2", "BING2", "Peminatan2", "Mean2", "Keterangan", "TransKeterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true, false, true, true, true, true, true, true, true, true, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblDatasetUji);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltotaldatauji)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbltotaldatauji))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PARAMETER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Cn", 0, 14))); // NOI18N

        buttonGroup1.add(multiTesting);
        multiTesting.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        multiTesting.setText("Multi Testing");
        multiTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiTestingActionPerformed(evt);
            }
        });

        buttonGroup1.add(singleTesting);
        singleTesting.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        singleTesting.setText("Single Testing");
        singleTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleTestingActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jLabel7.setText("Nilai Nearest Neighbor (K) :");

        txtKNN.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtKNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKNNActionPerformed(evt);
            }
        });
        txtKNN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKNNKeyTyped(evt);
            }
        });

        btnProses.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btnProses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/proses.png"))); // NOI18N
        btnProses.setText("PROSES");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        btnProses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnProsesKeyTyped(evt);
            }
        });

        lblerror.setFont(new java.awt.Font("Roboto Lt", 0, 12)); // NOI18N
        lblerror.setForeground(new java.awt.Color(255, 0, 0));
        lblerror.setText("PESAN ERROR");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multiTesting)
                    .addComponent(singleTesting))
                .addGap(42, 42, 42)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(txtKNN, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProses)
                        .addGap(18, 18, 18)
                        .addComponent(lblerror)))
                .addContainerGap(406, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKNN)
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(singleTesting)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiTesting))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProses)
                            .addComponent(lblerror))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("    Dataset Pengujian    ", jPanel2);

        jPanel19.setBackground(new java.awt.Color(59, 102, 145));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "CONFUSION MATRIX", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        tblCM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "Prediksi Lulus", "prediksi Tidak"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(tblCM);

        lblAkurasi.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblAkurasi.setForeground(new java.awt.Color(255, 255, 255));
        lblAkurasi.setText("Akurasi");

        lblRecall.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblRecall.setForeground(new java.awt.Color(255, 255, 255));
        lblRecall.setText("Recall");

        lblPrecision.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblPrecision.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecision.setText("Precision");

        lblNilaiK.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblNilaiK.setForeground(new java.awt.Color(255, 255, 255));
        lblNilaiK.setText("Tingkat Keberhasilan Sistem dengan Nilai (K) =");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane11)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecision)
                    .addComponent(lblRecall)
                    .addComponent(lblAkurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNilaiK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(lblNilaiK)
                .addGap(18, 18, 18)
                .addComponent(lblAkurasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRecall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecision)
                .addGap(40, 40, 40))
        );

        jPanel20.setBackground(new java.awt.Color(59, 102, 145));
        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "HASIL KLASIFIKASI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIS", "Target Class", "Karakteristik"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane13.setViewportView(tblResult);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "HASIL KLASIFIKASI"));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel15.setText("Table Hasil Klasifikasi tidak bisa dilihat pada saat Multi Testing");
        jPanel21.add(jLabel15, java.awt.BorderLayout.CENTER);

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CONFUSION MATRIX"));
        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.LINE_AXIS));

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel16.setText("Confusion Matrix tidak bisa dilihat pada saat Multi Testing");
        jPanel22.add(jLabel16);

        jPanel23.setBackground(new java.awt.Color(59, 102, 145));
        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "GRAFIK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        panelChart.setLayout(new java.awt.BorderLayout());

        panelChart2.setLayout(new java.awt.BorderLayout());

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane15.setViewportView(txtArea);

        panelChart2.add(jScrollPane15, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelChart2, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(panelChart, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelChart2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("            Hasil Evaluasi            ", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblTahunUjiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTahunUjiMouseClicked
        try {
            ce = new controlEvaluasi();
            ce.showDataSetTest(tblDatasetUji, tblTahunUji, lbltotaldatauji);
        } catch (SQLException ex) {
            Logger.getLogger(menuEvaluasi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblTahunUjiMouseClicked

    private void tblTahunModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTahunModelMouseClicked
        ce = new controlEvaluasi();
        try {
            ce.showDataSetModel(tblDatasetModel, tblTahunModel, lbltotaldataModel);
        } catch (SQLException ex) {
            Logger.getLogger(menuEvaluasi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblTahunModelMouseClicked

    private void btnProsesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnProsesKeyTyped
        ce = new controlEvaluasi();
        ce.validasiNumberofNearest(evt, txtKNN, lblerror, tblDatasetModel);
    }//GEN-LAST:event_btnProsesKeyTyped

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        ce = new controlEvaluasi();
        try {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            ce.proccessMining(tblDatasetModel, tblDatasetUji, txtKNN, lblerror, jTabbedPane1, tblResult, tblCM, tblTahunUji, lblAkurasi, lblNilaiK, lblPrecision, lblRecall, panelChart, panelChart2, panelChart2, singleTesting, multiTesting, txtArea);
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            if (multiTesting.isSelected()) {
                jPanel20.setVisible(false);
                jPanel19.setVisible(false);
                jPanel21.setVisible(false);//true
                jPanel22.setVisible(false);//true
                txtArea.setVisible(true);
            } else if (singleTesting.isSelected()) {
                jPanel20.setVisible(true);
                jPanel19.setVisible(true);
                jPanel21.setVisible(false);
                jPanel22.setVisible(false);
                txtArea.setVisible(false);
                jScrollPane15.setVisible(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(menuEvaluasi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProsesActionPerformed

    private void txtKNNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKNNKeyTyped
        ce = new controlEvaluasi();
        ce.validasiNumberofNearest(evt, txtKNN, lblerror, tblDatasetModel);
        if (multiTesting.isSelected()) {
            jPanel20.setVisible(false);
            jPanel19.setVisible(false);
            jPanel21.setVisible(true);
            jPanel22.setVisible(true);
        } else if (singleTesting.isSelected()) {
            jPanel20.setVisible(true);
            jPanel19.setVisible(true);
            jPanel21.setVisible(false);
            jPanel22.setVisible(false);
        }
    }//GEN-LAST:event_txtKNNKeyTyped

    private void txtKNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKNNActionPerformed
        try {
            // TODO add your handling code here:
            ce = new controlEvaluasi();
            ce.proccessMining(tblDatasetModel, tblDatasetUji, txtKNN, lblerror, jTabbedPane1, tblResult, tblCM, tblTahunUji, lblAkurasi, lblNilaiK, lblPrecision, lblRecall, panelChart, panelChart2, panelChart2, singleTesting, multiTesting, txtArea);
        } catch (SQLException ex) {
            Logger.getLogger(menuEvaluasi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtKNNActionPerformed

    private void singleTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleTestingActionPerformed
        if (singleTesting.isSelected()) {
            txtKNN.setEnabled(true);
            btnProses.setEnabled(true);
        }
    }//GEN-LAST:event_singleTestingActionPerformed

    private void multiTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiTestingActionPerformed
        if (multiTesting.isSelected()) {
            btnProses.setEnabled(true);
            txtKNN.setEnabled(false);
            lblerror.setText("");
            txtKNN.setText("");
        }
    }//GEN-LAST:event_multiTestingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAkurasi;
    private javax.swing.JLabel lblNilaiK;
    private javax.swing.JLabel lblPrecision;
    private javax.swing.JLabel lblRecall;
    private javax.swing.JLabel lblerror;
    private javax.swing.JLabel lbltotaldataModel;
    private javax.swing.JLabel lbltotaldatauji;
    private javax.swing.JRadioButton multiTesting;
    private javax.swing.JPanel panelChart;
    private javax.swing.JPanel panelChart2;
    private javax.swing.JRadioButton singleTesting;
    private javax.swing.JTable tblCM;
    private javax.swing.JTable tblDatasetModel;
    private javax.swing.JTable tblDatasetUji;
    private javax.swing.JTable tblResult;
    private javax.swing.JTable tblTahunModel;
    private javax.swing.JTable tblTahunUji;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtKNN;
    // End of variables declaration//GEN-END:variables
}
