/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author arief budiman
 */
public class menuAtas extends javax.swing.JPanel {

    /**
     * Creates new form panel2
     */
    
    FlowLayout layout =  new FlowLayout();
    menuDataset test1;
    menuEvaluasi test2;
    menuKlasifikasi test3;
    //test4 test4;
    
    public menuAtas() {
        initComponents();
        
        test1 = new menuDataset();
        test2 = new menuEvaluasi();
        test3 = new menuKlasifikasi();
        //test4 = new test4();
        DynamicPanelIPA.setLayout(layout);
       // GridBagConstraints c = new GridBagConstraints();
       // c.gridx = 0;
        //c.gridy = 0;
        DynamicPanelIPA.add(test1);
        //c.gridx = 0;
        //c.gridy = 0;
        DynamicPanelIPA.add(test2);
        DynamicPanelIPA.add(test3);
        //DynamicPanelIPA.add(test4);
        setColor(btnDataset);
        resetColor(btnEvaluasi);
      //  resetColor(btnBackup);
        resetColor(btnKlasifikasi);
        ind_dataset.setOpaque(true);
        ind_evaluasi.setOpaque(false);
        ind_klasifikasi.setOpaque(false);
       // ind_backup.setOpaque(false);
        test1.setVisible(true);
        test2.setVisible(false);
        test3.setVisible(false);
       // test4.setVisible(false);

    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(104,141,171));
    }
     
     void resetColor(JPanel panel){
         panel.setBackground(new Color(104,141,171));
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEvaluasi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ind_evaluasi = new javax.swing.JPanel();
        btnKlasifikasi = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ind_klasifikasi = new javax.swing.JPanel();
        btnDataset = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ind_dataset = new javax.swing.JPanel();
        DynamicPanelIPA = new javax.swing.JPanel();

        setBackground(new java.awt.Color(104, 141, 171));

        btnEvaluasi.setBackground(new java.awt.Color(104, 141, 171));
        btnEvaluasi.setPreferredSize(new java.awt.Dimension(131, 43));
        btnEvaluasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEvaluasiMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Evaluasi");

        ind_evaluasi.setBackground(new java.awt.Color(90, 204, 245));
        ind_evaluasi.setOpaque(false);
        ind_evaluasi.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout ind_evaluasiLayout = new javax.swing.GroupLayout(ind_evaluasi);
        ind_evaluasi.setLayout(ind_evaluasiLayout);
        ind_evaluasiLayout.setHorizontalGroup(
            ind_evaluasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );
        ind_evaluasiLayout.setVerticalGroup(
            ind_evaluasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btnEvaluasiLayout = new javax.swing.GroupLayout(btnEvaluasi);
        btnEvaluasi.setLayout(btnEvaluasiLayout);
        btnEvaluasiLayout.setHorizontalGroup(
            btnEvaluasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEvaluasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ind_evaluasi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEvaluasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
        );
        btnEvaluasiLayout.setVerticalGroup(
            btnEvaluasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEvaluasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ind_evaluasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnKlasifikasi.setBackground(new java.awt.Color(104, 141, 171));
        btnKlasifikasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKlasifikasiMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Klasifikasi");
        jLabel3.setPreferredSize(new java.awt.Dimension(122, 29));

        ind_klasifikasi.setBackground(new java.awt.Color(90, 204, 245));
        ind_klasifikasi.setOpaque(false);
        ind_klasifikasi.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout ind_klasifikasiLayout = new javax.swing.GroupLayout(ind_klasifikasi);
        ind_klasifikasi.setLayout(ind_klasifikasiLayout);
        ind_klasifikasiLayout.setHorizontalGroup(
            ind_klasifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );
        ind_klasifikasiLayout.setVerticalGroup(
            ind_klasifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btnKlasifikasiLayout = new javax.swing.GroupLayout(btnKlasifikasi);
        btnKlasifikasi.setLayout(btnKlasifikasiLayout);
        btnKlasifikasiLayout.setHorizontalGroup(
            btnKlasifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKlasifikasiLayout.createSequentialGroup()
                .addGroup(btnKlasifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnKlasifikasiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ind_klasifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnKlasifikasiLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnKlasifikasiLayout.setVerticalGroup(
            btnKlasifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKlasifikasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ind_klasifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnDataset.setBackground(new java.awt.Color(104, 141, 171));
        btnDataset.setPreferredSize(new java.awt.Dimension(131, 48));
        btnDataset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDatasetMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dataset");

        ind_dataset.setBackground(new java.awt.Color(90, 204, 245));
        ind_dataset.setOpaque(false);
        ind_dataset.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout ind_datasetLayout = new javax.swing.GroupLayout(ind_dataset);
        ind_dataset.setLayout(ind_datasetLayout);
        ind_datasetLayout.setHorizontalGroup(
            ind_datasetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );
        ind_datasetLayout.setVerticalGroup(
            ind_datasetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btnDatasetLayout = new javax.swing.GroupLayout(btnDataset);
        btnDataset.setLayout(btnDatasetLayout);
        btnDatasetLayout.setHorizontalGroup(
            btnDatasetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDatasetLayout.createSequentialGroup()
                .addGroup(btnDatasetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnDatasetLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ind_dataset, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnDatasetLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnDatasetLayout.setVerticalGroup(
            btnDatasetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDatasetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ind_dataset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DynamicPanelIPA.setBackground(new java.awt.Color(59, 102, 145));

        javax.swing.GroupLayout DynamicPanelIPALayout = new javax.swing.GroupLayout(DynamicPanelIPA);
        DynamicPanelIPA.setLayout(DynamicPanelIPALayout);
        DynamicPanelIPALayout.setHorizontalGroup(
            DynamicPanelIPALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DynamicPanelIPALayout.setVerticalGroup(
            DynamicPanelIPALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DynamicPanelIPA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnDataset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnEvaluasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnKlasifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(646, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEvaluasi, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btnKlasifikasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDataset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(DynamicPanelIPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatasetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatasetMousePressed
        // TODO add your handling code here:
        
        setColor(btnDataset);
        resetColor(btnEvaluasi);
      
        resetColor(btnKlasifikasi);
        ind_dataset.setOpaque(true);
        ind_evaluasi.setOpaque(false);
        ind_klasifikasi.setOpaque(false);
     
        test1.setVisible(true);
        test2.setVisible(false);
        test3.setVisible(false);
      //  test4.setVisible(false);
        
    }//GEN-LAST:event_btnDatasetMousePressed

    
    private void btnEvaluasiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEvaluasiMousePressed
        // TODO add your handling code here:
        setColor(btnEvaluasi);
        resetColor(btnDataset);
      
        resetColor(btnKlasifikasi);
        ind_evaluasi.setOpaque(true);
        ind_dataset.setOpaque(false);
        ind_klasifikasi.setOpaque(false);
     
        test2.setVisible(false);
        test2.setVisible(true);
        test1.setVisible(false);
        test3.setVisible(false);
      
        
        
    }//GEN-LAST:event_btnEvaluasiMousePressed

    private void btnKlasifikasiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKlasifikasiMousePressed
        // TODO add your handling code here:
        setColor(btnKlasifikasi);
        resetColor(btnDataset);
       
        resetColor(btnEvaluasi);
        ind_klasifikasi.setOpaque(true);
        ind_dataset.setOpaque(false);
        ind_evaluasi.setOpaque(false);
       // ind_backup.setOpaque(false);
        
        test3.setVisible(true);
        test1.setVisible(false);
        test2.setVisible(false);
        //test4.setVisible(false);
        
    }//GEN-LAST:event_btnKlasifikasiMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanelIPA;
    private javax.swing.JPanel btnDataset;
    private javax.swing.JPanel btnEvaluasi;
    private javax.swing.JPanel btnKlasifikasi;
    private javax.swing.JPanel ind_dataset;
    private javax.swing.JPanel ind_evaluasi;
    private javax.swing.JPanel ind_klasifikasi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
